### ISSUE TITLE
Turn UniqueMorphism into a CAP operation

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/Locales#71]
As discussed with @TKuh.

**Comment by mohamed-barakat** [comment]
The content of the various `ADD_COMMON_METHODS_FOR_*` in `Locales` can then be turned into derivations, and these global functions should be deleted. This should resolve two issues:
* setting the wrong properties for `TerminalCategoriesWithMultipleObjects` mentioned in https://github.com/homalg-project/CAP_project/pull/1039 and affecting https://github.com/homalg-project/CAP_project/pull/1009;
* get these trivial CAP operations for morphisms in a thin category out of the list of primitively installed operations, so they do not appear in the list of compiled primitive operations.

**Comment by zickgraf** [comment]
Regarding the first point: Would you get rid of the involved properties completely? If yes, why can't you do this already now? If no, how would this solve setting the wrong properties for `TerminalCategoriesWithMultipleObjects`?

**Comment by mohamed-barakat** [comment]
The wrong properties were set by these `ADD_COMMON_METHODS_FOR_*`. They are currently used to install methods that should in principle be derived, once there is an operation called `UniqueMorphism(WithWitness)`. I wanted to discuss the details with you anyway before changing `Locales` accordingly.

**Comment by mohamed-barakat** [comment]
@TKuh: I was wrong, I don't use `ADD_COMMON_METHODS_FOR_*` in the terminal category constructor.

**Comment by mohamed-barakat** [comment]
Together with @zickgraf we decided to turn `UniqueMorphism` into a CAP operation :)
